baseURL: "https://lewinno.github.io/" 
title: Lewin Nolden
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        
        - name: Research
          url: research/
          weight: 2
        - name: CV
          url: /cv/CV_Nolden.pdf
          weight: 3
        

params:
    description: ""
    author: Lewin Nolden
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Lewin Nolden
          subtitle: "I am a first year PhD student at the University of Oxford under the supervision of *[Barbara Petrongolo](https://sites.google.com/site/barbarapetrongolo/home)* and *[Johannes Abeler](https://sites.google.com/site/johannesabeler/)*."
          imageUrl: "picture.jpg"
          imageWidth: 220
          imageHeight: 220
          buttons:
            - name: Research
              url: research/
            - name: CV
              url: /cv/CV_Nolden.pdf

    socialIcons:
        - name: Email
          url: mailto:lewin.nolden@economics.ox.ac.uk
        - name: GitHub
          url: https://github.com/lewinno
        - name: LinkedIn
          url: https://www.linkedin.com/in/lewin-nolden-a05a591b4/
       

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Lewin Nolden"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2